<?php use Phalcon\Tag as Tag ?>

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf8">
        <link rel="shortcut icon" href="img/favicon.ico">
        <?php
            echo Tag::getTitle();
            echo Tag::stylesheetLink('bootstrap/css/bootstrap.css');
            echo Tag::stylesheetLink('bootstrap/css/bootstrap-responsive.css');
            echo Tag::stylesheetLink('css/style.css');
        ?>
        <meta name="viewport" content="width=device-width, intial-scale=1.0">
        <meta name="description" content="Phalcon bootstrap description here">
        <meta name="author" content="Copyright © Poohbah"
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Project name</a>
                </div>
                <div class="collapsenavbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="content">
                <?php echo $this->getContent(); ?>
            </div>
        </div>
        <?php
            echo Tag::javascriptInclude('js/jquery-1.11.1.js');
            echo Tag::javascriptInclude('bootstrap/js/bootstrap.js');
        ?>
    </body>
</html>
